# settings.yaml
repositories:
  database_path: "./repositories/database/app_database.db"
  external_db_path: "./repositories/database/external_db.db"
  external_img_dir: "./repositories/images"
  screen_shot_dir: "./repositories/screenshots"

  tiktok_path: "./repositories/apks/facebook.apk"
  facebook_path: "./repositories/apks/tiktok.apk"

apk_dir: "./apks"

logs:
  directory: "./logs"

redis:
  host: "localhost"
  port: 6379
  db: 0