# settings.yaml
repositories:
  database_path: "./repositories/database/app_database.db"
  # external_db_path: "/Volumes/KINGSTON/Ext_dev/python/my_manager.repositories/database/database.db"
  # external_img_dir: "/Volumes/KINGSTON/Ext_dev/python/my_manager.repositories/images_product"
  external_db_path: "C:/Users/dinhb/Desktop/repositories/db/database.db"
  external_img_dir: "C:/Users/dinhb/Desktop/repositories/images_products"
  screen_shot_dir: "./repositories/screenshots"

  tiktok_path: "./repositories/apks/facebook.apk"
  facebook_path: "./repositories/apks/tiktok.apk"

apk_dir: "./apks"

logs:
  directory: "./logs"

redis:
  host: "localhost"
  port: 6379
  db: 0